#!/bin/bash
set -euo pipefail
TASK_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$TASK_ROOT"
bash Scripts/build-worker.sh
swift build -c release
TASK_APP="$TASK_ROOT/build/Speech Wingman.next.app"
# A previously staged update may itself be running. Preserve that bundle too.
if pgrep -f "$TASK_APP/Contents/MacOS/SpeechWingman" >/dev/null; then
  printf 'The staged update is running. Quit it before rebuilding: %s\n' "$TASK_APP" >&2
  exit 1
fi
# This staging bundle is generated by this script and contains no user data.
rm -rf "$TASK_APP"
mkdir -p "$TASK_APP/Contents/MacOS" "$TASK_APP/Contents/Resources/Models" "$TASK_APP/Contents/Resources/lib" "$TASK_APP/Contents/Resources/Licenses"
cp .build/release/SpeechWingman "$TASK_APP/Contents/MacOS/SpeechWingman"
cp Resources/Info.plist "$TASK_APP/Contents/Info.plist"
cp -R Resources/en.lproj Resources/zh-Hans.lproj Resources/ja.lproj Resources/ko.lproj "$TASK_APP/Contents/Resources/"
cp build/native/bin/text-worker build/native/bin/asr-worker "$TASK_APP/Contents/Resources/"
cp Vendor/sherpa-onnx/lib/libonnxruntime.dylib Vendor/sherpa-onnx/lib/libsherpa-onnx-c-api.dylib "$TASK_APP/Contents/Resources/lib/"
install_name_tool -delete_rpath "$TASK_ROOT/Vendor/sherpa-onnx/lib" "$TASK_APP/Contents/Resources/asr-worker"
install_name_tool -add_rpath '@executable_path/lib' "$TASK_APP/Contents/Resources/asr-worker"
/usr/bin/python3 - <<'PY'
import json,pathlib,shutil
root=pathlib.Path('Models'); dest=pathlib.Path('build/Speech Wingman.next.app/Contents/Resources/Models')
for name in ['manifest-text.json','manifest-asr.json','manifest-vad.json']:
    manifest=json.loads((root/name).read_text())
    for item in manifest['files']:
        path=root/item['file']
        if not path.is_file() or path.stat().st_size != item['size']:
            raise SystemExit(f'Missing/incomplete {path}. Run Scripts/setup-model.py.')
        shutil.copy2(path,dest/path.name)
    shutil.copy2(root/name,dest/name)
license=root/'LICENSE-Qwen3-4B-Instruct-2507.txt'
shutil.copy2(license,dest/license.name)
PY
cp THIRD_PARTY_NOTICES.md Resources/asr-runtime.json "$TASK_APP/Contents/Resources/"
cp LICENSE "$TASK_APP/Contents/Resources/Licenses/SpeechWingman-MIT.txt"
cp Vendor/llama.cpp/LICENSE "$TASK_APP/Contents/Resources/Licenses/llama.cpp-MIT.txt"
cp Vendor/llama.cpp/licenses/LICENSE-jsonhpp "$TASK_APP/Contents/Resources/Licenses/"
cp Vendor/llama.cpp/common/base64.hpp "$TASK_APP/Contents/Resources/Licenses/"
cp Vendor/sherpa-onnx/LICENSE "$TASK_APP/Contents/Resources/Licenses/sherpa-onnx-Apache-2.0.txt"
cp Vendor/sherpa-onnx/LICENSE-onnxruntime Vendor/sherpa-onnx/ThirdPartyNotices-onnxruntime.txt "$TASK_APP/Contents/Resources/Licenses/"
for TASK_LIB in "$TASK_APP"/Contents/Resources/lib/*.dylib; do
  codesign --force --sign - "$TASK_LIB"
done
for TASK_WORKER in text-worker asr-worker; do
  codesign --force --sign - --entitlements Resources/Worker.entitlements "$TASK_APP/Contents/Resources/$TASK_WORKER"
done
codesign --force --sign - --entitlements Resources/App.entitlements "$TASK_APP"
codesign --verify --deep --strict "$TASK_APP"
# Replace only after the entire new bundle has built and passed signature verification.
if pgrep -x SpeechWingman >/dev/null; then
  printf 'Built update at %s. Quit the running app before opening this update; its current session was preserved.\n' "$TASK_APP"
  exit 0
fi
rm -rf "$TASK_ROOT/build/Speech Wingman.app"
mv "$TASK_APP" "$TASK_ROOT/build/Speech Wingman.app"
printf 'Built %s\n' "$TASK_ROOT/build/Speech Wingman.app"
